## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [1]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [2]:
# code here
pclass_groups = titanic_df.groupby("Pclass")
avg = pclass_groups['Age'].mean()
na_values = pclass_groups['Age'].apply(lambda x: x.isna().sum())
print(avg)
print(na_values)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64
Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [3]:
# code here
pclass_groups = titanic_df.groupby("Pclass")

titanic_df['Embarked'] = pclass_groups['Embarked'].transform(lambda x: x.fillna(x.mode()[0]))

print(titanic_df.groupby("Pclass")["Embarked"].value_counts(ascending=True))

Pclass  Embarked
1       Q             2
        C            85
        S           129
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [4]:
# code here
result = {}
embarked_groups = titanic_df.groupby("Embarked")
for embarked_group in list(embarked_groups.groups.keys()):
    pclass_groups = embarked_groups.get_group(embarked_group).groupby("Pclass")
    result[embarked_group] = {}
    for pclass_group in list(pclass_groups.groups.keys()):
        result[embarked_group][pclass_group] = round(pclass_groups.get_group(pclass_group)['Fare'].mean(), 2)
result

{'C': {1: np.float64(104.72), 2: np.float64(25.36), 3: np.float64(11.21)},
 'Q': {1: np.float64(90.0), 2: np.float64(12.35), 3: np.float64(11.18)},
 'S': {1: np.float64(70.51), 2: np.float64(20.33), 3: np.float64(14.64)}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [5]:
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [6]:
# code here
def z_normalization(group, cols):
    for col in cols:
        mean = group[col].mean()
        std = group[col].std()
        if std != 0:
            group[f"{col}_z_norm"] = (group[col] - mean) / std
        else:
            group[f"{col}_z_norm"] = 0
    return group


cols = ['Passes', 'Passes Completed', 'Attempted Line Breaks', 'Completed Line Breaks']

team_groups = fifa_df.groupby("Team", as_index=False)
normalized_fifa_df = team_groups.apply(z_normalization, cols=cols).groupby("Team")

team_stats = normalized_fifa_df.agg({
    "Passes": ['min', 'max'],
    "Yellow Cards": ['min', 'max', 'mean'],
    "Attempted Line Breaks": ['max', 'min', "std"],
    "Possession (%)": "mean"
})

team_stats

/tmp/ipykernel_531/4040150975.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  normalized_fifa_df = team_groups.apply(z_normalization, cols=cols).groupby("Team")

               Passes       Yellow Cards               Attempted Line Breaks  \
                  min   max          min max      mean                   max
Team
Argentina         408   862            0   8  2.285714                   249
Australia         286   466            0   3  1.750000                   171
Belgium           512   685            1   3  1.666667                   195
Brazil            548   695            0   3  1.200000                   193
Cameroon          295   500            1   5  2.666667                   182
Canada            448   536            2   4  2.666667                   176
Costa Rica        231   454            1   3  2.000000                   154
Croatia           461   724            0   2  1.142857                   259
Denmark           537   650            1   2  1.666667                   241
Ecuador           429   484            0   2  1.000000                   177
England           508   810            0   1  0.200000                   208
France            358   734            0   3  1.142857                   179
Germany           352   827            0   3  1.000000                   256
Ghana             319   460            2   4  2.666667                   188
Iran              232   463            2   3  2.333333                   195
Japan             225   591            0   3  1.500000                   253
Korea Republic    359   548            1   2  1.500000                   201
Mexico            356   500            1   4  2.333333                   198
Morocco           229   583            0   3  1.285714                   157
Netherlands       403   786            0   4  1.800000                   198
Poland            303   466            1   3  1.750000                   156
Portugal          461   678            0   3  1.200000                   197
Qatar             424   457            0   4  2.333333                   174
Saudi Arabia      267   560            2   6  4.666667                   205
Senegal           277   511            1   3  1.750000                   184
Serbia            403   513            2   7  4.000000                   184
Spain             647  1070            0   1  0.500000                   237
Switzerland       403   512            1   4  2.250000                   178
Tunisia           328   501            1   3  1.666667                   200
United States     427   572            0   4  1.250000                   204
Uruguay           390   528            1   3  2.000000                   186
Wales             325   508            1   2  1.666667                   208

                               Possession (%)
                min        std           mean
Team
Argentina       141  38.774685      49.285714
Australia       133  17.682383      31.250000
Belgium         167  14.422205      49.000000
Brazil          164  10.691118      50.400000
Cameroon        144  19.857828      38.333333
Canada          102  37.753587      44.333333
Costa Rica       86  38.974351      27.333333
Croatia          97  54.499891      47.428571
Denmark         173  34.000000      51.333333
Ecuador         143  17.009801      42.666667
England         133  29.676590      57.200000
France          126  21.407609      44.857143
Germany         143  56.624494      53.000000
Ghana           122  33.020196      37.000000
Iran             56  77.526340      31.666667
Japan           104  64.048810      30.250000
Korea Republic  139  27.072434      42.250000
Mexico          127  40.706265      46.666667
Morocco         128  10.641339      34.285714
Netherlands     168  12.759310      44.000000
Poland           79  36.326070      32.000000
Portugal        165  13.049904      53.800000
Qatar           159   7.767453      39.333333
Saudi Arabia    147  29.022979      36.666667
Senegal         143  16.938615      38.500000
Serbia          140  22.188586      42.666667
Spain           186  24.289916      67.000000
Switzerland     157   9.032349      43.000000
Tunisia         153  24.419937      38.666667
United States   143  27.693260      47.000000
Uruguay         146  22.030282      41.000000
Wales           104  53.028294      41.000000

## **Questions on IPL dataset**

ball by ball dataset - https://drive.usercontent.google.com/u/0/uc?id=1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt&export=download

In [8]:
ipl = pd.read_csv("https://drive.usercontent.google.com/u/0/uc?id=1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt&export=download")
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [9]:
# code here
second_innings = ipl[(ipl['innings'] == 2)]
batter_groups = second_innings.groupby(["ID", "batter"])


# highest score and batsman name
temp_df = batter_groups['batsman_run'].sum().reset_index()
result = temp_df.iloc[temp_df['batsman_run'].idxmax()]
print(result['batter'], "=>", result['batsman_run'])

# Best Strike rate while chasing and have faced 100+ balls
temp_df = ipl[~(ipl['extra_type']=="wides")]
temp_df = temp_df.groupby("batter").agg({
    "batsman_run": "sum",
    "ballnumber": "count"
})
temp_df["strike_rate"] = temp_df['batsman_run'] / temp_df['ballnumber'] * 100
result = temp_df[temp_df['ballnumber'] >= 100].sort_values("strike_rate", ascending=False)
result.head(1)

PC Valthaty => 120

            batsman_run  ballnumber  strike_rate
batter
AD Russell         2039        1147   177.768091

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [13]:
# code here
ipl["IsBatterOut"] = ipl.batter == ipl.player_out
bowler_batter = ipl.groupby(["bowler", "batter"])
bowler_batter.agg({
    "IsBatterOut": "sum",
    "batsman_run": "sum"
}).sort_values(by=["IsBatterOut", "batsman_run"], ascending=[False, True]).head()

                           IsBatterOut  batsman_run
bowler         batter
Z Khan         MS Dhoni              7           74
Sandeep Sharma V Kohli               7           78
A Mishra       RG Sharma             7           87
R Ashwin       RV Uthappa            7          123
SP Narine      RG Sharma             7          137

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [16]:
# code here
import numpy as np
def func(x):
    return '-'.join(list(np.sort(x.values)))

ipl["batter-pair"] = ipl[["batter", "non-striker"]].apply(func, axis=1)
ipl.groupby("batter-pair")["total_run"].sum().sort_values(ascending=False).head()

batter-pair
AB de Villiers-V Kohli    3134
CH Gayle-V Kohli          2802
DA Warner-S Dhawan        2357
G Gambhir-RV Uthappa      1906
KL Rahul-MA Agarwal       1731
Name: total_run, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [28]:
from tempfile import tempdir
# code here
temp_df = ipl.groupby("batter-pair").agg({
    "total_run": "sum",
    "ballnumber": "count",
    "isWicketDelivery": "sum"
}).reset_index()
temp_df["Batsman1"] = temp_df["batter-pair"].apply(lambda x: x.split("-")[0] )
temp_df["Batsman2"] = temp_df["batter-pair"].apply(lambda x: x.split("-")[1] )
temp_df.rename(columns={ "total_run": "Runs"}, inplace=True)
temp_df["StrikeRate"] = temp_df["Runs"] / temp_df["ballnumber"] * 100
temp_df["Avg"] = temp_df["Runs"] / temp_df["isWicketDelivery"]
temp_df.sort_values("Runs", ascending=False, inplace=True)
temp_df[["Batsman1", "Batsman2", "Runs", "Avg", "StrikeRate"]]

            Batsman1     Batsman2  Runs        Avg  StrikeRate
302   AB de Villiers      V Kohli  3134  44.140845  152.209811
1251        CH Gayle      V Kohli  2802  52.867925  142.017233
1508       DA Warner     S Dhawan  2357  48.102041  136.637681
1954       G Gambhir   RV Uthappa  1906  39.708333  133.754386
2803        KL Rahul   MA Agarwal  1731  52.454545  142.939719
...              ...          ...   ...        ...         ...
34       A Choudhary     S Badree     0   0.000000    0.000000
4215        T Stubbs  Tilak Varma     0   0.000000    0.000000
64          A Mishra     CL White     0   0.000000    0.000000
3114  M Muralitharan      MS Gony     0   0.000000    0.000000
3107        M Morkel     S Nadeem     0   0.000000    0.000000

[4259 rows x 5 columns]